[project]
name = "ccbfold"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alex Pickering", email = "alexvpickering@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
]

[project.scripts]
ccbfold = "ccbfold:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
